version: '3.8'

services:
  # MySQL 서비스
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - 'MYSQL_DATABASE=final'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Redis 서비스
  redis-stack-compose:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    environment:
      - REDIS_ARGS=--requirepass 1234
    ports:
      - 6379:6379
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
