name: Java CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # 4. Gradle 파일 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. MySQL 설정
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'final'
          mysql user: 'root'
          mysql password: ${{ secrets.MYSQL_PASSWORD }} # GitHub Secrets 탭에서 설정하세요!

      # 6. Docker Compose 설치
      - name: Install Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      # 7. Gradle 빌드 (테스트 단계 건너뜀)
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      # 8. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t kjs4231/balance-system .

      # 9. Docker Compose로 서비스 실행
      - name: Run Docker Compose services
        run: |
          docker-compose up -d
          sleep 15  # 모든 서비스가 완전히 시작되기를 기다림
          docker ps # 실행 중인 모든 컨테이너 확인

      # 11. Docker Hub 로그인 및 이미지 푸시 (옵션)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        if: success()
        run: docker push kjs4231/balance-system
